### ISSUE TITLE
txt File Ending for default LogFile

### ISSUE THREAD

**Issue by SeidChr** [PowershellGroup/Write-Log-Module#1]
https://github.com/PowershellGroup/Write-Log-Module/blob/39d6f9081bba4b640613a1b4cae22ec8c57b3714/Module/Write-Log/Write-Log.psm1#L44

Hey, filetype is usually .txt and not .log
Also log.log sound strange :)

**Comment by captainqwerty** [comment]
You can call the file anything I just used log as the name of the file as an example.
However .txt is a text file where as .log is for log files - either is appropriate I just like to store my logs as .log so its easier when searching for *.log to find log files.

But yes you are right, log.log does sound odd so in the minor update I am working on I will use a different example file name but I will also point out in the documentation you can use any text based file extension so can use .log or .txt :) 

I have labelled this as an enhancement and shall close it in the next minor update. 

Thank you.

**Comment by captainqwerty** [comment]
Resolved in version 1.1.0
